
<h2>Editar Tarea</h2>
<div class="container">
	<div class="col-sm-6 col-md-6 mx-auto">		
		<form action="<?php
		/**
		 * editar.phtml
		 *
		 * @author Arturo Adonay Rayas Vergara <arturorayas60@gmail.com>
		 */

		 echo APP_URL."tareas/editar"; ?>" method="POST">
			<input type="hidden" name="id" value="<?php echo $this->tarea["id"]; ?>">
			<div class="form-group">
				<label for="nombre">Nombre</label>
				<input type="text" name="nombre" class="form-control" value="<?php echo $this->tarea["nombre"]; ?>">
			</div>
			<div class="form-group">
				<label for="descripcion">Descripcion</label>
				<textarea name="descripcion" cols="10" rows="3" class="form-control"><?php echo $this->tarea["descripcion"]; ?>
				</textarea>
			</div>
			<div class="form-group">
				<label for="fecha">Fecha</label>
				<input type="date" name="fecha" class="form-control" value="<?php echo $this->tarea["fecha"]; ?>">
			</div>
			<div class="form-group">
				<label for="prioridad">Prioridad</label>
				<input type="range" name="prioridad" min="0" max="10" class="form-control" value="<?php echo $this->tarea["prioridad"]; ?>">
			</div>
			<div class="form-group">
				<label for="categoria">Categoria</label>
				<select name="categoria" class="form-control">
					<?php 
						foreach ($this->categorias as $categoria) {
							echo "<option value=".$categoria[0].">".$categoria[1]."</option>";
						}
					?>
				</select>
			</div>
			<div class="form-group">
				
			</div>
			<button type="submit" class="btn btn-primary mg-top-10">Guardar</button>
		</form>
	</div>
</div>
